version: "3.2"
services:
  sql-server-db:
    image: mcr.microsoft.com/azure-sql-edge:latest
    platform: linux/arm64/v8
    ports:
      - '${DB_PORT:-1433}:1433'
    networks:
      - backend
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: "StrongPassword1903@@"
      MSSQL_PID: "Developer"
    volumes:
      - ./storage/docker:/var/opt/mssql/backup
networks:
  backend:
    driver: bridge
